# Generated by Django 5.1.1 on 2024-09-06 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.PositiveIntegerField()),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Package_status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_person', models.CharField(max_length=100)),
                ('bill_address', models.TextField()),
                ('contact_phone', models.PositiveIntegerField()),
                ('ship_address', models.TextField()),
                ('preferred_shipping_date', models.DateField()),
                ('created_by', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Purchase_status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Sales_status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Ship_method',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Ship_status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact_person', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.PositiveIntegerField()),
                ('address', models.TextField()),
                ('since', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('address', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.TextField(unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('sku', models.CharField(max_length=100, unique=True)),
                ('purchasing_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('on_hand', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('units', models.CharField(max_length=50)),
                ('updated', models.DateTimeField()),
                ('reorder_point', models.PositiveIntegerField(null=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.brand')),
                ('preferred_supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.supplier')),
                ('warehouse', models.ManyToManyField(related_name='warehouse', to='inventory.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='Order_items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('P', 'Purchase'), ('O', 'Order')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField()),
                ('units', models.PositiveIntegerField()),
                ('item_id', models.ManyToManyField(to='inventory.inventory')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.purchase')),
            ],
        ),
        migrations.AddField(
            model_name='purchase',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.purchase_status'),
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responsible_person', models.CharField(max_length=100)),
                ('contact_person', models.CharField(max_length=100)),
                ('bill_address', models.TextField()),
                ('contact_phone', models.PositiveIntegerField()),
                ('ship_address', models.TextField()),
                ('preferred_shipping_date', models.DateField()),
                ('created_by', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.customer')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.sales_status')),
                ('ship_method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.ship_method')),
                ('Warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slip', models.PositiveIntegerField(auto_created=True)),
                ('created_at', models.DateTimeField()),
                ('packed_at', models.DateTimeField()),
                ('shipping_address', models.CharField(max_length=200)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.customer')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.package_status')),
                ('sales', models.ManyToManyField(to='inventory.sales')),
            ],
        ),
        migrations.AddField(
            model_name='purchase',
            name='ship_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.ship_method'),
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('shipment_address', models.CharField(max_length=200)),
                ('shipment_date', models.DateTimeField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.customer')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.package')),
                ('sales', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.sales')),
                ('ship_method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.ship_method')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.ship_status')),
            ],
        ),
        migrations.AddField(
            model_name='purchase',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.supplier'),
        ),
        migrations.CreateModel(
            name='Supplier_rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competency', models.SmallIntegerField(choices=[(1, 'Poor'), (2, 'Fair'), (3, 'Satisfactory'), (4, 'Good'), (5, 'Excellent')])),
                ('communication', models.SmallIntegerField(choices=[(1, 'Poor'), (2, 'Fair'), (3, 'Satisfactory'), (4, 'Good'), (5, 'Excellent')])),
                ('commitment', models.SmallIntegerField(choices=[(1, 'Poor'), (2, 'Fair'), (3, 'Satisfactory'), (4, 'Good'), (5, 'Excellent')])),
                ('transaction', models.SmallIntegerField(choices=[(1, 'Poor'), (2, 'Fair'), (3, 'Satisfactory'), (4, 'Good'), (5, 'Excellent')])),
                ('consistency', models.SmallIntegerField(choices=[(1, 'Poor'), (2, 'Fair'), (3, 'Satisfactory'), (4, 'Good'), (5, 'Excellent')])),
                ('cost', models.SmallIntegerField(choices=[(1, 'Poor'), (2, 'Fair'), (3, 'Satisfactory'), (4, 'Good'), (5, 'Excellent')])),
                ('supplier', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inventory.supplier')),
            ],
        ),
        migrations.AddField(
            model_name='purchase',
            name='Warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.warehouse'),
        ),
    ]
