# Generated by Django 5.1.1 on 2024-09-14 06:30

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('supplier', '0007_remove_supplier_supplier_supplier_rating'),
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ShipMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, unique=True, upload_to='items')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('sku', models.CharField(max_length=100, unique=True)),
                ('purchasing_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('on_hand', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('units', models.CharField(blank=True, max_length=50)),
                ('updated', models.DateTimeField(default=datetime.datetime.now)),
                ('reorder_point', models.PositiveIntegerField(default=5)),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.brand')),
                ('preferred_supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='supplier.supplier')),
                ('warehouse', models.ManyToManyField(related_name='items', to='warehouse.warehouse')),
            ],
        ),
    ]
