# Generated by Django 5.1.1 on 2024-09-06 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.brand'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='photo',
            field=models.FilePathField(unique=True),
        ),
    ]
