# Generated by Django 5.1.1 on 2024-09-15 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_inventory_brand'),
        ('supplier', '0008_alter_supplier_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='items'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='preferred_supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='supplier.supplier'),
        ),
    ]
