# Generated by Django 5.1.1 on 2024-09-06 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_inventory_updated_alter_purchase_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='photo',
            field=models.FilePathField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='units',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='warehouse',
            field=models.ManyToManyField(null=True, related_name='warehouse', to='inventory.warehouse'),
        ),
    ]
