# Generated by Django 5.1.1 on 2024-09-16 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_inventory_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='dimensions',
            field=models.CharField(default=123, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventory',
            name='weight',
            field=models.PositiveIntegerField(default=56),
            preserve_default=False,
        ),
    ]
