# Generated by Django 5.1.1 on 2024-09-18 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_inventory_dimensions_inventory_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='name',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
    ]
