# Generated by Django 5.1.1 on 2024-09-07 05:27

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_inventory_photo_alter_inventory_units_and_more'),
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='supplier.supplier'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='preferred_supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='supplier.supplier'),
        ),
        migrations.RemoveField(
            model_name='supplier_rating',
            name='supplier',
        ),
        migrations.AlterField(
            model_name='inventory',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 7, 10, 57, 1, 41857)),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 7, 10, 57, 1, 46807)),
        ),
        migrations.DeleteModel(
            name='Supplier',
        ),
        migrations.DeleteModel(
            name='Supplier_rating',
        ),
    ]
