# Generated by Django 5.1.1 on 2024-09-07 07:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_inventory_updated_alter_purchase_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 7, 13, 4, 10, 961264)),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='warehouse',
            field=models.ManyToManyField(related_name='warehouse', to='inventory.warehouse'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 7, 13, 4, 10, 965268)),
        ),
    ]
