# Generated by Django 5.1.1 on 2024-09-07 07:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_inventory_updated_alter_inventory_warehouse_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 7, 13, 14, 1, 838736)),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 7, 13, 14, 1, 842738)),
        ),
    ]
