# Generated by Django 5.1.1 on 2024-09-07 10:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_alter_inventory_updated_alter_purchase_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 7, 16, 20, 35, 174117)),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 7, 16, 20, 35, 176117)),
        ),
    ]
