# Generated by Django 5.1.1 on 2024-09-07 15:07

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_alter_inventory_updated_alter_purchase_created_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order_items',
            new_name='Sale_items',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='Warehouse',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='ship_method',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='status',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='supplier',
        ),
        migrations.AlterField(
            model_name='inventory',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 7, 20, 37, 34, 940882)),
        ),
        migrations.AlterField(
            model_name='sale_items',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.sales'),
        ),
        migrations.DeleteModel(
            name='Purchase_status',
        ),
        migrations.DeleteModel(
            name='Purchase',
        ),
    ]
