# Generated by Django 5.1.1 on 2024-09-08 07:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_alter_inventory_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='contact_person',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='contact_phone',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 8, 13, 18, 3, 852131)),
        ),
    ]
