# Generated by Django 5.1.1 on 2024-09-08 10:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_warehouse_contact_person_warehouse_contact_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 8, 15, 39, 24, 90398)),
        ),
    ]
