# Generated by Django 5.1.1 on 2024-09-09 15:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0024_alter_inventory_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipment',
            name='package',
        ),
        migrations.RemoveField(
            model_name='sale_items',
            name='item_id',
        ),
        migrations.RemoveField(
            model_name='sale_items',
            name='order',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='Warehouse',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='ship_method',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='status',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='sales',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='ship_method',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='status',
        ),
        migrations.AlterField(
            model_name='inventory',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 9, 21, 17, 56, 713870)),
        ),
        migrations.DeleteModel(
            name='Package',
        ),
        migrations.DeleteModel(
            name='Sale_items',
        ),
        migrations.DeleteModel(
            name='Sales_status',
        ),
        migrations.DeleteModel(
            name='Sales',
        ),
        migrations.DeleteModel(
            name='Shipment',
        ),
    ]
