# Generated by Django 5.1.1 on 2024-09-09 16:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0025_remove_shipment_package_remove_sale_items_item_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 9, 21, 48, 20, 441263)),
        ),
    ]
