# Generated by Django 5.1.1 on 2024-09-11 07:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0041_alter_inventory_updated'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ship_status',
        ),
        migrations.AlterField(
            model_name='inventory',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 11, 13, 15, 24, 990201)),
        ),
    ]
