# Generated by Django 5.1.1 on 2024-09-15 17:22

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_inventory_photo_and_more'),
        ('purchase_orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='contact_phone',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='preferred_shipping_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='ship_method',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.shipmethod'),
        ),
    ]
