# Generated by Django 5.1.1 on 2024-09-15 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_inventory_photo_and_more'),
        ('purchase_orders', '0003_purchasedraft_alter_purchaseorder_total_amount_and_more'),
        ('supplier', '0008_alter_supplier_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseitems',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='purchasesitems',
            name='supplier',
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='supplier.supplier'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='contact_phone',
            field=models.PositiveIntegerField(default=37863490),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='ship_method',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='inventory.shipmethod'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=4234, max_digits=10),
            preserve_default=False,
        ),
    ]
