# Generated by Django 5.1.1 on 2024-09-08 06:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_orders', '0003_alter_purchase_created_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='Warehouse',
            new_name='warehouse',
        ),
        migrations.AlterField(
            model_name='purchase',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 8, 12, 14, 28, 691451)),
        ),
    ]
