# Generated by Django 5.1.1 on 2024-09-08 07:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_orders', '0004_rename_warehouse_purchase_warehouse_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 8, 13, 18, 3, 857887)),
        ),
    ]
