# Generated by Django 5.1.1 on 2024-09-15 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_orders', '0005_purchasedraft_supplier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='supplier',
        ),
    ]
