# Generated by Django 5.1.1 on 2024-09-08 10:09

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_alter_inventory_updated'),
        ('purchase_orders', '0005_alter_purchase_created_date'),
        ('supplier', '0005_remove_supplier_rating_supplier_rating_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 8, 15, 39, 24, 114117)),
        ),
        migrations.CreateModel(
            name='Purchase_draft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_person', models.CharField(max_length=100)),
                ('bill_address', models.TextField()),
                ('contact_phone', models.PositiveIntegerField()),
                ('ship_address', models.TextField()),
                ('preferred_shipping_date', models.DateField()),
                ('created_by', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField(default=datetime.datetime(2024, 9, 8, 15, 39, 24, 113012))),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ship_method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.ship_method')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='supplier.supplier')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.warehouse')),
            ],
        ),
        migrations.AlterField(
            model_name='purchase',
            name='id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='purchase_orders.purchase_draft'),
        ),
    ]
