# Generated by Django 5.1.1 on 2024-09-08 12:58

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_alter_inventory_updated'),
        ('purchase_orders', '0006_alter_purchase_created_date_purchase_draft_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='purchase_orders.purchase_items'),
        ),
        migrations.RemoveField(
            model_name='purchase_items',
            name='order',
        ),
        migrations.AlterField(
            model_name='purchase',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 8, 18, 28, 25, 474995)),
        ),
        migrations.RemoveField(
            model_name='purchase_items',
            name='item_id',
        ),
        migrations.AlterField(
            model_name='purchase_items',
            name='units',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='Purchase_draft',
        ),
        migrations.AddField(
            model_name='purchase_items',
            name='item_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.inventory'),
        ),
    ]
