# Generated by Django 5.1.1 on 2024-09-22 14:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_orders', '0006_remove_purchaseorder_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
