# Generated by Django 5.1.1 on 2024-09-08 12:59

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_orders', '0007_alter_purchase_id_remove_purchase_items_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 8, 18, 29, 37, 737597)),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='purchase_orders.purchase_items'),
        ),
    ]
