# Generated by Django 5.1.1 on 2024-09-26 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_orders', '0007_purchaseorder_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='created_date',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='updated',
            field=models.DateTimeField(),
        ),
    ]
