# Generated by Django 5.1.1 on 2024-09-09 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_orders', '0008_alter_purchase_created_date_alter_purchase_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase_items',
            name='item_id',
        ),
        migrations.DeleteModel(
            name='Purchase',
        ),
        migrations.DeleteModel(
            name='Purchase_items',
        ),
    ]
