# Generated by Django 5.1.1 on 2024-09-27 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_orders', '0008_alter_purchaseorder_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='created_date',
            field=models.DateTimeField(),
        ),
    ]
