# Generated by Django 5.1.1 on 2024-09-09 09:24

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_alter_inventory_updated'),
        ('purchase_orders', '0009_remove_purchase_items_item_id_delete_purchase_and_more'),
        ('supplier', '0005_remove_supplier_rating_supplier_rating_supplier'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase_items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('P', 'Purchase'), ('O', 'Order')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField()),
                ('units', models.CharField(max_length=50)),
                ('item_id', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.inventory')),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='purchase_orders.purchase_items')),
                ('contact_person', models.CharField(max_length=100)),
                ('bill_address', models.TextField()),
                ('contact_phone', models.PositiveIntegerField()),
                ('ship_address', models.TextField()),
                ('preferred_shipping_date', models.DateField()),
                ('created_by', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField(default=datetime.datetime(2024, 9, 9, 14, 54, 16, 869923))),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ship_method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.ship_method')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='purchase_orders.purchase_status')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='supplier.supplier')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.warehouse')),
            ],
        ),
    ]
