# Generated by Django 5.1.1 on 2024-09-29 11:39

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_orders', '0009_alter_purchaseorder_created_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiveStatus',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameModel(
            old_name='Purchase_status',
            new_name='PurchaseStatus',
        ),
        migrations.RemoveField(
            model_name='purchasereceive',
            name='order',
        ),
        migrations.AddField(
            model_name='purchasereceive',
            name='ref',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='receive', to='purchase_orders.purchasedraft'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchasereceive',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 29, 17, 9, 54, 574324)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='purchasereceive',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='purchase_orders.receivestatus'),
        ),
    ]
