# Generated by Django 5.1.1 on 2024-09-09 09:47

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0022_alter_inventory_updated'),
        ('purchase_orders', '0010_purchase_items_purchase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 9, 15, 17, 16, 473679)),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='preferred_shipping_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='purchase_items',
            name='item_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.inventory'),
        ),
    ]
