# Generated by Django 5.1.1 on 2024-09-09 13:08

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_orders', '0011_alter_purchase_created_date_and_more'),
        ('supplier', '0005_remove_supplier_rating_supplier_rating_supplier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='supplier',
        ),
        migrations.AddField(
            model_name='purchase_items',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='supplier.supplier'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 9, 18, 38, 36, 68738)),
        ),
    ]
