# Generated by Django 5.1.1 on 2024-09-30 05:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_orders', '0011_purchaseorder_cancel'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasereceive',
            name='cancel',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='purchasereceive',
            name='ref',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recieve', to='purchase_orders.purchasedraft'),
        ),
    ]
