# Generated by Django 5.1.1 on 2024-09-09 15:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_orders', '0012_remove_purchase_supplier_purchase_items_supplier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 9, 20, 57, 8, 584165)),
        ),
    ]
