# Generated by Django 5.1.1 on 2024-09-11 05:38

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_orders', '0024_alter_purchase_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 11, 11, 8, 13, 910392)),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='order', serialize=False, to='purchase_orders.purchase_items'),
        ),
    ]
