# Generated by Django 5.1.1 on 2024-09-11 05:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_orders', '0025_alter_purchase_created_date_alter_purchase_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 11, 11, 17, 34, 621778)),
        ),
    ]
