# Generated by Django 5.1.1 on 2024-09-13 08:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_orders', '0040_alter_purchase_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 13, 14, 24, 53, 773794)),
        ),
    ]
