# Generated by Django 5.1.1 on 2024-09-14 06:40

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
        ('inventory', '0001_initial'),
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageStatus',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SalesStatus',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ShipStatus',
            fields=[
                ('id', models.SmallIntegerField(default=1, primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales_person', models.CharField(max_length=100)),
                ('bill_address', models.TextField()),
                ('contact_phone', models.PositiveIntegerField(null=True)),
                ('ship_address', models.TextField()),
                ('preferred_shipping_date', models.DateTimeField(null=True)),
                ('created_by', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField(default=datetime.datetime.now)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('updated', models.DateTimeField(default=datetime.datetime.now)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='customer.customer')),
                ('ship_method', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.shipmethod')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.warehouse')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='sales_orders.salesstatus')),
            ],
        ),
        migrations.CreateModel(
            name='SaleItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bm_create_uuid', models.UUIDField(db_index=True, default=None, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField()),
                ('units', models.CharField(max_length=50)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='customer.customer')),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.inventory')),
                ('sales', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales_orders.sales')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SalesItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField()),
                ('units', models.CharField(max_length=50)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='customer.customer')),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='inventory.inventory')),
                ('sales', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales_orders.sales')),
            ],
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.PositiveBigIntegerField(editable=False)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('shipment_address', models.CharField(max_length=200)),
                ('shipment_date', models.DateTimeField(null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customer.customer')),
                ('sales', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipment', to='sales_orders.sales')),
                ('ship_method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.shipmethod')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='sales_orders.shipstatus')),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('packed_at', models.DateTimeField(null=True)),
                ('shipping_address', models.CharField(max_length=200)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customer.customer')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sales_orders.packagestatus')),
                ('sales', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package', to='sales_orders.sales')),
                ('ship', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='package', to='sales_orders.shipment')),
            ],
        ),
    ]
