# Generated by Django 5.1.1 on 2024-09-09 15:47

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0025_remove_shipment_package_remove_sale_items_item_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sales_status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales_person', models.CharField(max_length=100)),
                ('bill_address', models.TextField()),
                ('contact_phone', models.PositiveIntegerField()),
                ('ship_address', models.TextField()),
                ('preferred_shipping_date', models.DateTimeField()),
                ('created_by', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField(default=datetime.datetime(2024, 9, 9, 21, 17, 56, 760230))),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.customer')),
                ('ship_method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.ship_method')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.warehouse')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sales_orders.sales_status')),
            ],
        ),
        migrations.CreateModel(
            name='Sales_items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField()),
                ('units', models.CharField(max_length=50)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.customer')),
                ('item_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='inventory.inventory')),
                ('sales', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales_orders.sales')),
            ],
        ),
    ]
