# Generated by Django 5.1.1 on 2024-09-15 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesitems',
            name='customer',
        ),
        migrations.AddField(
            model_name='sales',
            name='offer',
            field=models.PositiveSmallIntegerField(default=0, max_length=3),
        ),
        migrations.AddField(
            model_name='salesitems',
            name='discount',
            field=models.PositiveSmallIntegerField(default=0, max_length=3),
        ),
    ]
