# Generated by Django 5.1.1 on 2024-09-15 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_orders', '0002_remove_salesitems_customer_sales_offer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitems',
            name='discount',
            field=models.PositiveSmallIntegerField(default=0, max_length=3),
        ),
    ]
