# Generated by Django 5.1.1 on 2024-09-09 16:28

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0029_alter_inventory_updated'),
        ('sales_orders', '0002_alter_sales_created_date_sale_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 9, 21, 58, 23, 801388)),
        ),
        migrations.AlterField(
            model_name='sales',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.customer'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='ship_method',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.ship_method'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='sales_orders.sales_status'),
        ),
    ]
