# Generated by Django 5.1.1 on 2024-09-09 16:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_orders', '0003_alter_sales_created_date_alter_sales_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='contact_phone',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 9, 22, 0, 59, 126633)),
        ),
    ]
