# Generated by Django 5.1.1 on 2024-09-15 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_orders', '0004_remove_saleitems_customer_alter_saleitems_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='ship',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='package', to='sales_orders.shipment'),
        ),
    ]
