# Generated by Django 5.1.1 on 2024-09-09 16:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_orders', '0004_alter_sales_contact_phone_alter_sales_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 9, 22, 2, 9, 647940)),
        ),
        migrations.AlterField(
            model_name='sales',
            name='preferred_shipping_date',
            field=models.DateTimeField(null=True),
        ),
    ]
