# Generated by Django 5.1.1 on 2024-09-15 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_orders', '0005_alter_package_ship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='sales',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shipment', to='sales_orders.sales'),
        ),
    ]
