# Generated by Django 5.1.1 on 2024-09-16 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_orders', '0006_alter_shipment_sales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleitems',
            name='discount',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='salesitems',
            name='discount',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
