# Generated by Django 5.1.1 on 2024-09-22 14:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_orders', '0007_alter_saleitems_discount_alter_salesitems_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='shipment',
            name='update',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='package',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
