# Generated by Django 5.1.1 on 2024-09-10 04:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_orders', '0007_alter_sales_created_date_alter_sales_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 10, 10, 6, 4, 637931)),
        ),
        migrations.AlterField(
            model_name='sales_status',
            name='id',
            field=models.SmallAutoField(primary_key=True, serialize=False),
        ),
    ]
