# Generated by Django 5.1.1 on 2024-09-10 04:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_orders', '0008_alter_sales_created_date_alter_sales_status_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 10, 10, 7, 56, 990966)),
        ),
        migrations.AlterField(
            model_name='sales_status',
            name='id',
            field=models.SmallIntegerField(primary_key=True, serialize=False),
        ),
    ]
