# Generated by Django 5.1.1 on 2024-09-22 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_orders', '0008_package_updated_shipment_update_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shipment',
            old_name='update',
            new_name='updated',
        ),
    ]
