# Generated by Django 5.1.1 on 2024-09-30 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_inventory_name'),
        ('sales_orders', '0009_rename_update_shipment_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('units', models.CharField(max_length=50)),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='package', to='inventory.inventory')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales_orders.package')),
            ],
        ),
        migrations.CreateModel(
            name='PackItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bm_create_uuid', models.UUIDField(db_index=True, default=None, null=True)),
                ('quantity', models.PositiveIntegerField()),
                ('units', models.CharField(max_length=50)),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.inventory')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item', to='sales_orders.package')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
