# Generated by Django 5.1.1 on 2024-10-02 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_orders', '0010_packageitems_packitems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='sales_orders.salesstatus'),
            preserve_default=False,
        ),
    ]
