# Generated by Django 5.1.1 on 2024-10-05 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_orders', '0011_alter_sales_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='cancel',
            field=models.BooleanField(default=False),
        ),
    ]
