# Generated by Django 5.1.1 on 2024-09-11 07:02

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_orders', '0012_package_status_alter_sales_created_date_package'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='sales',
        ),
        migrations.AlterField(
            model_name='sales',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 11, 12, 32, 46, 439268)),
        ),
        migrations.AddField(
            model_name='package',
            name='sales',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='package', to='sales_orders.sales'),
        ),
    ]
