# Generated by Django 5.1.1 on 2024-09-11 07:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_orders', '0014_remove_package_slip_alter_sales_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='packed_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 11, 12, 34, 12, 709219)),
        ),
    ]
