# Generated by Django 5.1.1 on 2024-09-11 07:47

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0044_alter_inventory_updated'),
        ('sales_orders', '0017_alter_sales_created_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ship_status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='sales',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 11, 13, 17, 5, 2505)),
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('shipment_address', models.CharField(max_length=200)),
                ('shipment_date', models.DateTimeField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.customer')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales_orders.package')),
                ('sales', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales_orders.sales')),
                ('ship_method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.ship_method')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sales_orders.ship_status')),
            ],
        ),
    ]
