# Generated by Django 5.1.1 on 2024-09-11 08:53

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_orders', '0018_ship_status_alter_sales_created_date_shipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='tracking_number',
            field=models.PositiveBigIntegerField(default=1297349237523, editable=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sales',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 11, 14, 21, 48, 942182)),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 11, 14, 21, 48, 944189)),
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='sales',
        ),
        migrations.AlterField(
            model_name='shipment',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='sales_orders.ship_status'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='sales',
            field=models.ManyToManyField(related_name='shipment', to='sales_orders.sales'),
        ),
    ]
