# Generated by Django 5.1.1 on 2024-09-11 10:29

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_orders', '0020_alter_sales_created_date_alter_shipment_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipment',
            name='package',
        ),
        migrations.AddField(
            model_name='package',
            name='ship',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.PROTECT, related_name='package', to='sales_orders.shipment'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sales',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 11, 15, 59, 44, 164932)),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 11, 15, 59, 44, 166938)),
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='sales',
        ),
        migrations.AddField(
            model_name='shipment',
            name='sales',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipment', to='sales_orders.sales'),
        ),
    ]
