# Generated by Django 5.1.1 on 2024-09-11 10:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_orders', '0021_remove_shipment_package_package_ship_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 11, 16, 1, 29, 40969)),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 11, 16, 1, 29, 43015)),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='shipment_date',
            field=models.DateTimeField(null=True),
        ),
    ]
