# Generated by Django 5.1.1 on 2024-09-11 15:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_orders', '0022_alter_sales_created_date_alter_shipment_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 11, 21, 21, 50, 654821)),
        ),
        migrations.AlterField(
            model_name='ship_status',
            name='id',
            field=models.SmallIntegerField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 11, 21, 21, 50, 656848)),
        ),
    ]
