# Generated by Django 5.1.1 on 2024-09-11 18:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_orders', '0023_alter_sales_created_date_alter_ship_status_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 12, 0, 8, 33, 982540)),
        ),
        migrations.AlterField(
            model_name='sales',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 12, 0, 8, 33, 982540)),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 12, 0, 8, 33, 984112)),
        ),
    ]
