# Generated by Django 5.1.1 on 2024-09-13 08:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_orders', '0024_sales_updated_alter_sales_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 13, 14, 7, 29, 438771)),
        ),
        migrations.AlterField(
            model_name='sales',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 13, 14, 7, 29, 438771)),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 13, 14, 7, 29, 441882)),
        ),
    ]
