# Generated by Django 5.1.1 on 2024-09-13 12:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_orders', '0027_alter_sales_created_date_alter_sales_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 13, 18, 10, 57, 177593)),
        ),
        migrations.AlterField(
            model_name='sales',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 13, 18, 10, 57, 177593)),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 13, 18, 10, 57, 180593)),
        ),
    ]
