# Generated by Django 5.1.1 on 2024-09-18 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_notifications_delete_nofifications'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notifications',
            options={'ordering': ['-created']},
        ),
    ]
