# Generated by Django 5.1.1 on 2024-09-27 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_notifications_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
