# Generated by Django 5.1.1 on 2024-09-17 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_manager_phone_alter_specialist_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialist',
            name='specialist_id',
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(blank=True, upload_to='documents'),
        ),
        migrations.DeleteModel(
            name='Manager',
        ),
        migrations.DeleteModel(
            name='Specialist',
        ),
    ]
