# Generated by Django 5.1.1 on 2024-09-07 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact_person', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.PositiveIntegerField()),
                ('address', models.TextField()),
                ('since', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Supplier_rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competency', models.SmallIntegerField(choices=[(1, 'Poor'), (2, 'Fair'), (3, 'Satisfactory'), (4, 'Good'), (5, 'Excellent')])),
                ('communication', models.SmallIntegerField(choices=[(1, 'Poor'), (2, 'Fair'), (3, 'Satisfactory'), (4, 'Good'), (5, 'Excellent')])),
                ('commitment', models.SmallIntegerField(choices=[(1, 'Poor'), (2, 'Fair'), (3, 'Satisfactory'), (4, 'Good'), (5, 'Excellent')])),
                ('transaction', models.SmallIntegerField(choices=[(1, 'Poor'), (2, 'Fair'), (3, 'Satisfactory'), (4, 'Good'), (5, 'Excellent')])),
                ('consistency', models.SmallIntegerField(choices=[(1, 'Poor'), (2, 'Fair'), (3, 'Satisfactory'), (4, 'Good'), (5, 'Excellent')])),
                ('cost', models.SmallIntegerField(choices=[(1, 'Poor'), (2, 'Fair'), (3, 'Satisfactory'), (4, 'Good'), (5, 'Excellent')])),
                ('supplier', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='supplier.supplier')),
            ],
        ),
    ]
