# Generated by Django 5.1.1 on 2024-09-07 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0002_remove_supplier_rating_supplier_supplier_supplier'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplier',
            old_name='supplier',
            new_name='rating',
        ),
    ]
