# Generated by Django 5.1.1 on 2024-09-07 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0003_rename_supplier_supplier_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='rating',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplier', to='supplier.supplier_rating'),
        ),
    ]
