# Generated by Django 5.1.1 on 2024-09-08 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0004_alter_supplier_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='rating',
        ),
        migrations.AddField(
            model_name='supplier_rating',
            name='supplier',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='supplier.supplier'),
        ),
    ]
