# Generated by Django 5.1.1 on 2024-09-13 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0006_remove_supplier_rating_supplier_supplier_supplier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='supplier',
        ),
        migrations.AddField(
            model_name='supplier',
            name='rating',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplier', to='supplier.supplier_rating'),
        ),
    ]
